crusp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('studio.urls', namespace='studio')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studio/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views


urlpatterns = [
    url(r'^$', views.index, name='Index'),
    url(r'^(?P<pk>\d+)/$', views.portfolio, name='project_detail'),
    url(r'^contact-send/$', views.contact_form, name="contact_form"),
]

studio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Project name')
    title = models.CharField(max_length=500, verbose_name='Project title')
    main_image = models.ImageField(upload_to='projects/%Y/%m/%d/', verbose_name="Main image")
    description = models.TextField(verbose_name='Project description')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'
        ordering = ['name']

    def __str__(self):
        return self.name


class ProjectImage(models.Model):
    project = models.ForeignKey(Project, related_name='project', verbose_name='Project')
    image = models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name="Image for content")

    class Meta:
        verbose_name = 'Image'
        verbose_name_plural = 'Images'

studio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project, ProjectImage
from .form import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.


def index(request):
    projects = Project.objects.all()

    return render(request, 'crusp/index.html', context= {'projects': projects})


def portfolio(request, pk):
    project = get_object_or_404(Project, pk=pk)
    project_images = ProjectImage.objects.filter(project=project)
    projects_slider = Project.objects.all()

    return render(request, 'crusp/portfolio.html', context={
        "project": project,
        "project_images": project_images,
        "projects_slider": projects_slider,
    })


def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            ae = "{},\n {},\n {}\n".format(message, email, name)

            recepients = ['yourmail@gmail.com']

            try:
                send_mail(name, ae, 'yourmail@gmail.com', recepients)
            except BadHeaderError:
                return HttpResponse('Invalid header found')

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    else:
        form = ContactForm()

studio/templates/crusp/portfolio.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>Portfolio</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/portfolio.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js"></script>
    </head>
    <body>
        <header>
            <div class="navbar portfolio_header_box">
                <div class="portfolio_header_box_logo"><a href="{% url "studio:Index" %}">crusp</a></div>
            </div>
        </header>
        <div class="h1"><h1>Our work</h1></div>
        <section>
         <div class="portfolio_section">
                    <img class="portfolio_first_image" alt="all" src="{{ project.main_image.url }}" ></img>
                    <div class="portfolio_first_text">{{ project.title }}</div>
                <div class="portfolio_block">
                    <div class="portfolio_second_text">{{ project.description }}</div>

                    {% for image_project in project_images %}

                        <img class="portfolio_second_image" alt="all" src="{{ image_project.image.url }}" ></img>

                    {% endfor %}

                </div>
            </div>
    </section>
    <div class="portfolio_other">
        <p class="portfolio_other_text">All projects</p>
        <div class="portfolio_other_block">
                <div class="title-content">
                    <input  type="checkbox" class="click-target" id="f1"/>
                        <label for="f1">
                            <img class="title_content_img" src="{% static 'img/push.PNG' %}" alt="нажми"/>
                        </label>
                </div>
                      <div class="hidden-content">
                              <div class="row">
                                      <div class="customNavigation">
                                          <a class="btn gray prev"><img src="{% static 'img/left.PNG' %}" alt="previous"/></a>
                                          <!--<a class="btn gray next"><i class="icon ion-ios-arrow-right"></i></a>-->
                                      </div>
                                      <div id="slider-carousel" class="owl-carousel">

                                          {% for project_slide in projects_slider %}
                                              <div class="item">
                                                  <a class="hoverfx" href="{% url 'studio:project_detail' pk=project_slide.pk %}">
                                                    <div class="figure">
                                                        <i class="icon ion-search">{{ project_slide.title }}</i>
                                                    </div>
                                              <!--<div class="figure">
                                              <i class="icon ion-link"></i>
                                              </div>-->
                                                      <div class="overlay"></div>
                                              <img src="{{ project_slide.main_image.url }}">
                                                 </a>
                                                  <h4>{{ project_slide.name }}</h4>
                                          <!--<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat</p>-->
                                              </div>

                                          {% endfor %}

                                      </div>
                                      <div class="customNavigation">
                                            <a class="btn gray next"><img src="{% static "img/right.PNG" %}" alt="next"/></a>
                                        </div>
                                  </div>
                      </div>
        </div>
    </div>
    <footer>
        <div class="portfolio_footer">©  2018  Crusp studio</div>
    </footer>
    <script>
            $(document).ready(function () {
            $(".click-target").click(function(){
            $(this).parent().next(".hidden-content").slideToggle(1300); });});
    </script>
    <script>
            $(document).ready(function() {
            var owl = $("#slider-carousel");
            owl.owlCarousel({
            items: 4,
            itemsDesktop: [1000, 4],
            itemsDesktopSmall: [900, 2],
            itemsTablet: [600, 1],
            itemsMobile: false,
            pagination: false
            });
            $(".next").click(function() {
            owl.trigger('owl.next');
            })
            $(".prev").click(function() {
            owl.trigger('owl.prev');
            })
            });
    </script>
    </body>
</html>

studio/templates/crusp/portfolio2.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>Portfolio</title>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/portfolio.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js"></script>
    </head>
    <body>
        <header>
            <div class="navbar portfolio_header_box">
                <a href="{% url 'studio:Index' %}">
                    <div class="portfolio_header_box_logo">crusp</div>
                </a>
            </div>
        </header>
        <div class="h1"><h1>{{ project.name }}</h1></div>
        <section>
        <div class="portfolio_section">
                    <img class="portfolio_first_image" alt="all" src="{{ project.main_image.url }}" ></img>
                    <div class="portfolio_first_text">{{ project.title }}</div>
                <div class="portfolio_block">
                    <div class="portfolio_second_text">{{ project.description }}</div>

                    {% for image_project in project_images %}

                        <img class="portfolio_second_image" alt="all" src="{{ image_project.image.url }}" ></img>

                    {% endfor %}

                </div>
            </div>
    </section>
    <div class="portfolio_other">
        <h2>All projects</h2>
        <div class="portfolio_other_block">
                <div class="title-content">
                        <input  type="checkbox" class="click-target" id="f1"/>
                          <label for="f1">
                              <img src="push.png" alt="нажми"/>
                          </label>
                      </div>
                      <div class="hidden-content">
                              <div class="row">
                                      <div class="customNavigation">
                                          <a class="btn gray prev"><img src="left.png" alt="previous"/></a>
                                          <!--<a class="btn gray next"><i class="icon ion-ios-arrow-right"></i></a>-->
                                      </div>
                                      <div id="slider-carousel" class="owl-carousel">

                                          {% for project_slide in projects_slider %}
                                              <div class="item">
                                                  <a class="hoverfx" href="{% url 'studio:project_detail' pk=project_slide.pk %}">
                                                    <div class="figure">
                                                        <i class="icon ion-search">{{ project_slide.title }}</i>
                                                    </div>
                                              <!--<div class="figure">
                                              <i class="icon ion-link"></i>
                                              </div>-->
                                                      <div class="overlay"></div>
                                              <img src="{{ project_slide.main_image.url }}">
                                                 </a>
                                                  <h4>{{ project_slide.name }}</h4>
                                          <!--<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat</p>-->
                                              </div>

                                          {% endfor %}
                                      
                                      </div>
                                      <div class="customNavigation">
                                            <a class="btn gray next"><img src="right.png" alt="next"/></a>
                                        </div>
                                  </div>
                      </div>
        </div>
    </div>
    <footer>
        <div class="portfolio_footer">©  2018  Crusp studio</div>
    </footer>
    <script>
            $(document).ready(function () {
            $(".click-target").click(function(){
            $(this).parent().next(".hidden-content").slideToggle(1300); });});
    </script>
    <script>
            $(document).ready(function() {
            var owl = $("#slider-carousel");
            owl.owlCarousel({
            items: 4,
            itemsDesktop: [1000, 4],
            itemsDesktopSmall: [900, 2],
            itemsTablet: [600, 1],
            itemsMobile: false,
            pagination: false
            });
            $(".next").click(function() {
            owl.trigger('owl.next');
            })
            $(".prev").click(function() {
            owl.trigger('owl.prev');
            })
            });
    </script>
    </body>
</html>